<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite TODOS" duration-ms="25049" started-at="2020-09-15T21:57:22Z" finished-at="2020-09-15T21:57:47Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="25049" started-at="2020-09-15T21:57:22Z" finished-at="2020-09-15T21:57:47Z">
      <class name="com.todo.tests.AddTodoTest">
        <test-method status="PASS" signature="setupTest(java.lang.String)[pri:0, instance:com.todo.tests.AddTodoTest@212bf671]" name="setupTest" is-config="true" duration-ms="22105" started-at="2020-09-15T23:57:22Z" finished-at="2020-09-15T23:57:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="FAIL" signature="iCanAddTodo()[pri:0, instance:com.todo.tests.AddTodoTest@212bf671]" name="iCanAddTodo" duration-ms="814" started-at="2020-09-15T23:57:44Z" finished-at="2020-09-15T23:57:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.todo.tests.AddTodoTest.iCanAddTodo(AddTodoTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- iCanAddTodo -->
        <test-method status="PASS" signature="CleanTest()[pri:0, instance:com.todo.tests.AddTodoTest@212bf671]" name="CleanTest" is-config="true" duration-ms="2104" started-at="2020-09-15T23:57:44Z" finished-at="2020-09-15T23:57:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CleanTest -->
      </class> <!-- com.todo.tests.AddTodoTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite TODOS -->
</testng-results>
